### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by pawllo01** [ShinyId3Tagger/Shiny-ID3-Tagger#38] opened 2019-08-09 12:36 UTC
Hi,
Your software is not working... Are you planning to update it/fix it or this is an ended project?

**Comment by rluvaton** [comment] 2019-08-09 12:38
> Hi,
> Your software is not working... Are you planning to update it/fix it or this is an ended project?

@pawllo01 can you please add more information about what’s wrong (like is there an error or some action not working etc...)?

**Comment by pawllo01** [comment] 2019-08-09 15:01
I got an error like here:
https://github.com/ShinyId3Tagger/Shiny-ID3-Tagger/issues/37
When it scans music or when I go to User Settings. What can I do?
And will you update this software with features that has been listed?

**Comment by rluvaton** [comment] 2019-08-13 13:52
working on it

**Comment by rluvaton** [comment] 2019-08-13 16:09
The `develop` branch work, I just need to fix some little bugs and merge

**Comment by pawllo01** [comment] 2019-08-13 19:16
Ok, but what can I do with my bug? Do I have to wait for the next update?

**Comment by rluvaton** [comment] 2019-08-13 19:17
> Ok, but what can I do with my bug? Do I have to wait for the next update?

Unfortunately yes, hopefully it will be fixed until the end of the week

**Comment by rluvaton** [comment] 2019-08-19 13:33
I'm so busy at my work, I don't know if I have time to fix the bug, I hope that some of you can contribute to fix this

**Comment by rluvaton** [comment] 2019-09-08 10:52
Duplicate of #37

**Closed by rluvaton** 2019-09-08 10:52 UTC
Labels: bug
